services:
  db:
    image: postgres:16
    container_name: order_service_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  migrator:
    image: kukymbr/goose-docker:3.24.2
    container_name: migrator-order
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=${GOOSE_DBSTRING}
      - GOOSE_MIGRATION_DIR=${GOOSE_MIGRATION_DIR}
    volumes:
      - ./migrations:/migrations
    networks:
      - app-network
    command: up

  kafka:
    image: apache/kafka:latest
    container_name: kafka-image-processor
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_CLUSTER_ID: sz5Woq_TRNSbo-pElZnJ6Q
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    volumes:
      - kafka:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  kafka-init:
    image: apache/kafka:latest
    depends_on:
      - kafka
    entrypoint: [ "bash", "-c" ]
    command: |
      "
      echo 'Waiting for Kafka to be ready...';
      until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1; do
        sleep 5;
      done;
      echo 'Creating topic my-topic';
      /opt/kafka/bin/kafka-topics.sh --create --topic orders --partitions 1 --replication-factor 1 --bootstrap-server kafka:9092;
      echo 'Topic created, exiting...';
      exit 0
      "
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order_service_backend
    ports:
      - "8080:8080"
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    networks:
      - app-network

  producer:
    build:
      context: .
      dockerfile: Dockerfile-producer
    container_name: order_service_producer
    depends_on:
      backend:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKERS=${KAFKA_BROKERS}
    networks:
      - app-network
    command: ["sh", "-c", "sleep 10 && ./producer"]

volumes:
  postgres_data:
  kafka:

networks:
  app-network:
    driver: bridge
